services:
  # mysql:
  #   image: mysql:8.0
  #   container_name: quote-service-mysql
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: ${DB_NAME}
  #     MYSQL_USER: ${DB_USER}
  #     MYSQL_PASSWORD: ${DB_PASSWORD}
  #   ports:
  #     - "3307:3306"
  #   volumes:
  #     - ./_data/mysql-data:/var/lib/mysql
  #   healthcheck:
  #     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
  #     timeout: 20s
  #     retries: 10

  restapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quote-service-restapi
    restart: unless-stopped
    environment:
      VERSION: ${VERSION}
      HOST: ${HOST}
      PORT: ${PORT}
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      AUTHOR_SERVICE_URL: ${AUTHOR_SERVICE_URL}
    ports:
      - '8081:${PORT}'
    depends_on:
      mysql:
        condition: service_healthy
