services:
  restapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quote-service-restapi
    restart: unless-stopped
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      AUTHOR_SERVICE_URL: ${AUTHOR_SERVICE_URL}
    ports:
      - '${PORT}:${PORT}'
