apiVersion: v1
kind: Service
metadata:
  name: quote-service
  namespace: quote-app
  labels:
    app: quote-service
spec:
  type: ClusterIP
  selector:
    app: quote-service
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
